name: digital_krishi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.7

  flutter_local_notifications: ^19.5.0 
  http: ^1.1.0
  intl: ^0.20.2
  flutter_tts: ^4.2.3
  connectivity_plus: ^5.0.2
  speech_to_text: ^7.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.70.0
  permission_handler: ^12.0.1
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  image: ^4.1.3
  shared_preferences: ^2.2.3
  flutter_staggered_animations: ^1.1.1 
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  hive_generator: ^2.0.1
  flutter_markdown: ^0.7.2
  google_generative_ai: ^0.4.7
  url_launcher: ^6.1.10
  supabase_flutter: ^2.5.0
  flutter_animate: ^4.1.0
  lottie: ^2.7.0
  provider: ^6.1.2
  pytorch_lite: ^4.0.0

  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/app_Splash.png
    - assets/queries/intents.json
    - assets/log_page/plants_bg.jpg

    # crops
    - assets/crops/beans.png
    - assets/crops/beetroot.png
    - assets/crops/brinjal.png
    - assets/crops/cabbage.png
    - assets/crops/carrot.png   
    - assets/crops/corn.png 
    - assets/crops/cucumber.png  
    - assets/crops/green_chilli.png
    - assets/crops/okra.png
    - assets/crops/onion.png
    - assets/crops/pumpkin.png
    - assets/crops/radish.png
    - assets/crops/rice.png
    - assets/crops/snake_gourd.png
    - assets/crops/spinach.png
    - assets/crops/tomato.png

    # icons
    - assets/icons/pest.png
    - assets/icons/chat.png
    - assets/icons/fertilizer.png
    - assets/icons/irrigation.png
    - assets/icons/market.png
    - assets/icons/calendar.png
    - assets/icons/recommendation.png
    - assets/icons/subsidy.png


    # models
    - assets/models/mobile_model.ptl
    - assets/models/labels.txt



flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png" 

flutter_native_splash:
  color: "#1747A3"  # Background color (ARGB 255,23,71,163 as per your requirement)
  image: assets/app_Splash.png
  android: true
  ios: true
  web: false